feat: add ErrTooManyRequests to support Retry-After and 429
ipfs/go-libipfs pull request #194
Opened 2023-03-03 10:45 UTC by hacdias

This closes #188.

- Moved all - I think - logic related to errors to `errors.go`. I also added some simply sanity tests for this new error as it is its own custom type to support the `RetryAfter` field.
- Added `gateway.ErrTooManyRequests`. Returning an error of this type will make the gateway return 429. If the field `RetryAfter` above 0, it will set the `Retry-After` header. Also added a more "e2e" test for this, albeit arguable unnecessary since I added tests for `webError`.

2023-03-03 14:07 UTC, lidel requested changes

2023-03-03 14:07 UTC, lidel commented on gateway/errors.go
> +	}
I assume this was for debug? I'd remove it – this will be spamming logs too much.

2023-03-03 14:07 UTC, lidel commented on gateway/errors.go
> +	RetryAfter uint64
nit:  switch to time.Duration like we do [here](https://github.com/filecoin-saturn/caboose/blob/98dc6074d2940302f61c23a870adc86d681cbbee/caboose.go#L106).
consistency + makes things easier to work with if we need to round things to full seconds

We also want helpersm this will help us avoid writing the same boilerplate everywhere (would refactor caboose to use this):


- `func (e *ErrToomanyRequests) RetryAfterRoundSeconds() time.Duration` doing `RetryAfter.Round(time.Second)`
- `func (e *ErrToomanyRequests) RetryAfterHuman() string` which does `RetryAfterRoundSeconds.String()` (human-readable string rounded to full seconds like `5m` `1h30s`)
- `func (e *ErrToomanyRequests) RetryAfterHeader() string` which does `strconv.Itoa(int(RetryAfterRoundSeconds.Seconds()))` (the value for `Retry-After` HTTP header)

2023-03-06 04:01 UTC, lidel approved these changes
:thought_balloon: something I've realized during this review is that `Retry-After` is not limited to 429 Too Many Requests, which is used when user is sending too many requests. There are cases where  `Retry-After` is returned with  503 Service Unavailable (when it is not specific to user or their IP, could be global outage). 

Pushed two commits which replace all standalone errors with generic wrappers: `ErrorResponse` and `ErrorRetryAfter`, and attempted to wire that up in https://github.com/ipfs/bifrost-gateway/pull/56  – existing tests pass and does the trick, but I feel we could simplify things somehow.

@hacdias lmk if you have any idea how to make this better (if not, we can merge as-is, to unblock `Retry-After`, and refine later)

2023-03-06 08:44 UTC, merged

2023-03-06 08:44 UTC, hacdias commented
@lidel I think the way you rewrote it is a good idea. I'm not sure how we could simplify this now, but maybe later we will figure something out. Merged for now.