fix(gateway): 500 on panic, recover on WithHostname
ipfs/go-libipfs pull request #199
Opened 2023-03-08 19:48 UTC by mathew-cf

By default, go will write a 200 status code if none is written. During a panic, a 500 is more appropriate. This will be a no-op if the status code has already been written.

2023-03-09 09:04 UTC, hacdias approved these changes
This will also likely emit a `http: superfluous response.WriteHeader` in case something has already been written to the client. I think that is a fine trade-off to ensure that the client receives a 500 when there is a panic though. Thoughts @lidel?

2023-03-13 13:23 UTC, guseggert commented
Can we add a test for this?

2023-03-13 13:24 UTC, guseggert requested changes
Can we add a test for this?

2023-03-16 15:23 UTC, hacdias commented
@guseggert I stepped on here and added a test myself. Also, added the panic handler to the `WithHostname` middleware. As of right now, if `GetDNSLinkRecord` panics, there's no error recovery.

2023-03-16 15:55 UTC, guseggert approved these changes

2023-03-16 15:56 UTC, merged