Streamed pins
ipfs/go-libipfs pull request #290
Opened 2023-05-05 14:54 UTC by MichaelMure

The rational is that if the pin list get big, a synchronous call to get the complete list can delay handling unnecessarily. For example, when listing indirect pins, you can start walking the DAGs immediately with the first recursive pin instead of waiting for the full list.

This matters even more on low power device, of if the pin list is stored remotely.

Also in this PR, a DAG generator to simplify testing (used in the kubo PR to test the GC).

2023-05-25 22:43 UTC, BigLep commented
@MichaelMure : I know this has been open for awhile.  Apologies.  Maintainers spoke on 2023-05-25.  We'll make sure this goes out with Kubo 0.21.

Slack context: https://filecoinproject.slack.com/archives/C03L0G3B4RX/p1684507196595209

2023-06-02 02:10 UTC, Jorropo requested changes
I'll do the rebase on `main`, LGTM.

2023-06-02 02:10 UTC, Jorropo commented on coreiface/tests/pin.go
> +		}
```suggestion
		if err := r.Err(); err != nil {
			t.Error(err)
		}
```

2023-06-02 02:10 UTC, Jorropo commented on pinning/pinner/dspinner/pin.go
> +
```suggestion
```

2023-06-02 02:10 UTC, Jorropo commented on pinning/pinner/dspinner/pin_test.go
> +			}
```suggestion
		for val := range ch {
```

2023-06-02 02:15 UTC, Jorropo approved these changes
LGTM I'll test on Kubo

2023-06-02 08:38 UTC, hacdias commented
@Jorropo what's the status?

2023-06-02 14:49 UTC, merged