feat: reusable ipns verify
ipfs/go-libipfs pull request #292
Opened 2023-05-09 13:26 UTC by laurentsenta

Extracts the ipns verification code out of kubo to boxo,

this makes the verification code reusable, for example, with gateway-conformance testing (https://github.com/ipfs/gateway-conformance/pull/37)

Relates to https://github.com/ipfs/specs/issues/376

2023-05-09 14:25 UTC, hacdias requested changes
I think this is reasonable. This package will likely be refactored at some point in the near future when the lean records get more attention: https://github.com/ipfs/specs/issues/376

Small ask: can we change the following lines to use `UnmarshalIpnsEntry`?

https://github.com/ipfs/boxo/blob/8059f183d86648f69ad562546b4797bc148c0984/gateway/handler_ipns_record.go#L53-L54

2023-05-10 07:44 UTC, hacdias approved these changes

2023-05-10 07:46 UTC, hacdias approved these changes
As I stated previously, I think this is a reasonable change. It will likely be [refactored](https://github.com/ipfs/specs/issues/376) until the end of the year, but it's good to keep this functionality together.

2023-05-10 07:54 UTC, hacdias commented
Sharness failing because something changed in Kubo. We need to update Boxo there first, then we can merge this: https://github.com/ipfs/kubo/pull/9868

2023-05-10 08:19 UTC, merged

2023-05-10 08:23 UTC, Jorropo commented
This makes sense but I am suprised that this is being merged with 0 coverage in `entries.go`.

2023-05-10 08:27 UTC, hacdias commented
@Jorropo indeed, I was thinking of reverting this.

2023-05-10 08:35 UTC, hacdias commented
@laurentsenta I merged this too impulsively. It is reverted in #293. Do you mind opening this again with this change, but this time, also:

1. Add tests for the validation function.
2. Let's discuss the types
	a. `IpnsInspectEntry` was made specially for the `ipns name inspect` command, may not make sense here.
	b. `IpnsInspectValidation` was named after the command too, we can have a simpler and more generic name here.