Bitswap introspectability
ipfs/go-libipfs pull request #413
Opened 2023-07-20 14:53 UTC by Jorropo

Fixes  #209

- [ ] Peer Prom Tracker example
- [ ] Tracer tests, I think the client's tracer is bugged and it does not record outbound messages
- [ ] Changelog

2023-07-24 16:02 UTC, lidel requested changes

2023-07-24 16:02 UTC, lidel commented on bitswap/peer-prom-tracker/peer-prom-tracker.go
> +	peerIdLabel := []string{"peer-id"}
:warning:  This will create a separate time series per PeerID, which is ok for debugging, but should NOT be enabled by default. 

High cardinality labels in prometheus are  is considered antipattern. If there was 20K of peers, this will create 20K time series, and that may cause  problems (performance, billing) when Grafana tries to visualize it.

To understand why high cardinality is a problem, see:
- https://stackoverflow.com/questions/46373442/how-dangerous-are-high-cardinality-labels-in-prometheus
- https://grafana.com/blog/2022/10/20/how-to-manage-high-cardinality-metrics-in-prometheus-and-kubernetes/ 

IMO this PR can't land in boxo in this form as it creates footgun for users of this library.

There needs to be either a hard-limit on the number of peers tracked, or an explicit opt-in via constructor option or ENV variable.

2023-07-24 21:23 UTC, lidel commented on bitswap/peer-prom-tracker/peer-prom-tracker.go
> +	peerIdLabel := []string{"peer-id"}
:though I think if we wanted to merge metrics like this, we could measure P95 globally without running into cardinality problem.

To do so, one would define `Objectives` in `SummaryOpts` to be  P50, P75, P95 etc, and calculate `messages-received`, `messages-sent`, `bytes-received` etc  across all peers, not specific per peer. This way we get useful P95 metric with known error margin, without exploding the time series.

2023-07-27 09:57 UTC, Jorropo commented
This was comunicated as not needed and we don't want to run it in production in Kubo due to the cardinality issue.
So I'll close this an leave the branch in case it comes back up later.

2023-07-27 09:57 UTC, closed without merging