fix!: query escape abspath header
ipfs/go-libipfs pull request #434
Opened 2023-08-15 13:09 UTC by hacdias

See https://github.com/ipfs/kubo/issues/10065 and https://github.com/golang/go/issues/60674.

2023-08-16 07:27 UTC, Jorropo requested changes
So after discussions with @aschmahmann about concerns of silent breaking changes and @hacdias about fixing this, we are gonna go with this solution for binary file names in the `ipfs add` endpoint:
- leave current `abspath` header as-is, this header wont support binary encoded filepaths anymore due to the change in golang std;
- add a new `abspath-percent` header that is exactly like `abspath` but `url.QueryEscape`ed, kubo will then prefer using `abspath-percent` if present but use `abspath` if not
- new clients will send both headers

This gives us this compatibility table:
|            | New Client                            | Old Client                    |
|------------|---------------------------------------|-------------------------------|
| New Server | Works fully through `abspath-percent` | Binary file paths do not work  |
| Old Server | Works fully through `abspath`         | Works fully through `abspath` |

I don't know if headers are lazily or not decoded, so we might need to add an other response header indicating if `abspath-percent` is supported and do a HEAD request to identify if we are talking to a new or old server.

2023-08-16 10:11 UTC, hacdias commented
Just to note that the current PR is not yet ready. We do need to do a `HEAD` request or something to verify if we're talking to a new or old server since the headers are not lazy decoded.

2023-08-16 12:16 UTC, Jorropo commented
I was thinking the server would have a new `Support-Percent-Abspath-Header` then `NewMultiFileReader` would start with a `HEAD` request. I guess this would be less efficient because we would need to check each time, or cache it once.
I think a new option is fine as long as you follow the functional option parameters (so it defaults to `%` encoding unless you explicitly ask it not to)

2023-08-17 14:02 UTC, Jorropo approved these changes
LGTM

2023-08-17 14:02 UTC, Jorropo commented on CHANGELOG.md
> +  | Old Server | ✅         | ✅          |
```suggestion
  |            | New Client | Old Client  |
  |------------|------------|-------------|
  | New Server | ✅         | *🟡         |
  | Old Server | ✅         | ✅          |
  *Old clients can only send ASCII file paths to the server.
```

2023-08-17 14:02 UTC, Jorropo commented on CHANGELOG.md
> +  | Old Server | ✅         | ✅          |
Actually do you know if it is ASCII or unicode ?

2023-08-17 20:23 UTC, lidel requested changes
Seems to be missing test for non-ASCII?
(+ might be simplified – see comment inline, but that is fine to disregard)

2023-08-17 20:23 UTC, lidel commented on files/multifilereader.go
> +				}
@hacdias unsure if useful, but there is prior art in HTTP stack for doing this kind of thing without introducing a new header.

We could implement signaling convention from [RFC6266](https://httpwg.org/specs/rfc6266.html) and keep a single  `abspath` header + remove need for passing `rawAbsPath bool`. 

This way we have one header and:

- If filename is ascii-only, nothing changes:
  ```
  Abspath:  resume.txt
  ```
- If we have non-ASCII characters, like `résumé.txt` then we do `url.QueryEscape` AND  prefix it with `utf-8''`: 
  ```
  Abspath:  utf-8''r%C3%A9sum%C3%A9.txt
  ```

Receiving end knows if they need to un-escape based on the presence of `utf-8''` prefix.

Just food for thought.

2023-08-17 20:23 UTC, lidel commented on files/multifilereader_test.go
> +		do(t, false)
:warning: we only have tests for ASCII, would be good to add  separate one for `résumé.txt` to truly test `abspath-encoded`

2023-08-18 05:46 UTC, hacdias commented on files/multifilereader.go
> +				}
@lidel we won't need `rawAbsPath`, but we still need some variable. Old servers won't know what is a `utf-8`.

2023-08-21 08:40 UTC, hacdias commented on CHANGELOG.md
> +  | Old Server | ✅         | ✅          |
@Jorropo from my tests it seems to be Unicode.

2023-08-21 08:51 UTC, hacdias commented on files/multifilereader.go
> +				}
That considered, I don't think this would necessarily simplify. What do you think?

2023-08-21 08:52 UTC, hacdias commented
~~@lidel, as asked (makes sense), I added tests with the new header and **binary filenames**. Surprise surprise: our CI is still running on Go 1.19 for `go this`. Therefore, all tests will fail on `go this` and pass on `go next`. Therefore, this is likely blocked by #431 unless we want to be merging failing tests.~~

Fixed with separate tests with tags as per @Jorropo's suggestion.

2023-08-21 12:42 UTC, hacdias commented on files/readerfile.go
> +func NewBytesFileWithPath(abspath string, b []byte) File {
Maybe I should unexport is.

2023-08-21 13:07 UTC, lidel commented on files/multifilereader.go
> +				}
Agree, keeping two headers covers more edge cases with the smallest amount of work. 
We can use `utf-8''` thing in the future, but for now let's keep `abspath-encoded`.

(This header is only used with [`--nocopy` from Filestore, which is still marked  as experiment](https://github.com/ipfs/kubo/blob/master/docs/experimental-features.md#ipfs-filestore) in Kubo)

2023-08-21 14:43 UTC, lidel approved these changes
The tests look hairy, but acceptable given this header is only used for [experimental filestore feature in Kubo](https://github.com/ipfs/kubo/blob/master/docs/experimental-features.md#ipfs-filestore).  We will have to revisit code related to `--nocopy` at some point anyway, good for now.
Small nit inline but lgtm.

2023-08-21 14:43 UTC, lidel commented on files/multifilereader_binary_go119_test.go
> +//go:build !go1.20
:thought_balloon:  @hacdias would it be better to have `go1.19` here to avoid the problem when we try to build with `go1.21`? my understanding is that 21 will behave the same way as 20, and we don't need to worry about <19.
```suggestion
//go:build go1.19
```

2023-08-21 14:43 UTC, lidel commented on files/multifilereader_binary_go120_test.go
> +//go:build go1.20
```suggestion
//go:build !go1.19
```

2023-08-21 14:59 UTC, Jorropo commented on files/multifilereader_binary_go119_test.go
> +//go:build !go1.20
the `go1.20` tag will be set in 1.21 too.
Your suggestion is not wrong it just do nothing.

2023-08-21 15:00 UTC, Jorropo commented on files/multifilereader_binary_go120_test.go
> +//go:build go1.20
This is wrong `go1.19` is set when building with 1.20 or 1.21 so this will only trigger for `1.18` and bellow.
Generally the tag `go1.X` is set for releases of go `>= 1.X`.

2023-08-21 15:35 UTC, hacdias commented on files/multifilereader_binary_go119_test.go
> +//go:build !go1.20
I'm marking this as resolved due to @Jorropo explanation.

2023-08-21 15:35 UTC, hacdias commented on files/multifilereader_binary_go120_test.go
> +//go:build go1.20
I'm marking this as resolved due to @Jorropo explanation.

2023-08-21 15:39 UTC, hacdias commented
@Jorropo @lidel we need to **release** this before we bubble up to https://github.com/ipfs/go-ipfs-api/pull/305 and https://github.com/ipfs/go-ipfs-cmds/pull/243 so we don't have commit tags.

2023-08-21 16:06 UTC, merged